export type ExerciseCategory =
  | "strength"
  | "running"
  | "cardio"
  | "swimming"
  | "outdoor"
  | "mobility"
  | "mindbody"
  | "sports";

export type TrackingMode = "sets" | "distance" | "duration" | "swim";

export interface Exercise {
  id: string;
  name: string;
  aliases: string[];
  category: ExerciseCategory;
  group: string;
  equipment: string;
  muscles: string[];
  tracking: TrackingMode;
  popular?: boolean;
}

export const CATEGORY_META: Record<
  ExerciseCategory,
  { label: string; color: string }
> = {
  strength: { label: "力量", color: "#ff9b73" },
  running: { label: "跑步", color: "#8ee8dc" },
  cardio: { label: "有氧", color: "#68a9ff" },
  swimming: { label: "游泳", color: "#69d5ff" },
  outdoor: { label: "户外", color: "#b8e986" },
  mobility: { label: "拉伸恢复", color: "#d6a8ff" },
  mindbody: { label: "身心", color: "#f8cf72" },
  sports: { label: "球类运动", color: "#ff7fb2" },
};

type GroupInput = {
  prefix: string;
  category: ExerciseCategory;
  tracking: TrackingMode;
  group: string;
  equipment: string;
  muscles: string[];
  names: string[];
  popular?: string[];
};

function group(input: GroupInput): Exercise[] {
  return input.names.map((raw, index) => {
    const [name, aliasText = ""] = raw.split("|");
    return {
      id: `${input.prefix}-${String(index + 1).padStart(2, "0")}`,
      name,
      aliases: aliasText ? aliasText.split("/") : [],
      category: input.category,
      group: input.group,
      equipment: input.equipment,
      muscles: input.muscles,
      tracking: input.tracking,
      popular: input.popular?.includes(name),
    };
  });
}

export const EXERCISES: Exercise[] = [
  ...group({
    prefix: "barbell-compound",
    category: "strength",
    tracking: "sets",
    group: "杠铃复合动作",
    equipment: "杠铃",
    muscles: ["胸", "背", "腿", "肩", "核心"],
    popular: ["杠铃深蹲", "杠铃卧推", "传统硬拉", "站姿杠铃推举"],
    names: [
      "杠铃深蹲|背杠深蹲/Back Squat",
      "前蹲|杠铃前蹲/Front Squat",
      "箱式深蹲",
      "泽奇深蹲|Zercher Squat",
      "杠铃卧推|平板卧推/Bench Press",
      "上斜杠铃卧推",
      "下斜杠铃卧推",
      "窄握杠铃卧推",
      "传统硬拉|Conventional Deadlift",
      "相扑硬拉|Sumo Deadlift",
      "罗马尼亚硬拉|RDL",
      "直腿硬拉",
      "站姿杠铃推举|Overhead Press/OHP",
      "借力推举|Push Press",
      "杠铃划船|俯身划船",
      "潘德雷划船|Pendlay Row",
      "杠铃臀推|Hip Thrust",
      "早安式|Good Morning",
      "杠铃箭步蹲",
      "杠铃保加利亚分腿蹲",
      "高翻|Power Clean",
      "抓举|Snatch",
      "挺举|Clean and Jerk",
      "高拉|High Pull",
    ],
  }),
  ...group({
    prefix: "dumbbell-upper",
    category: "strength",
    tracking: "sets",
    group: "哑铃上肢",
    equipment: "哑铃",
    muscles: ["胸", "背", "肩", "手臂"],
    popular: ["哑铃卧推", "单臂哑铃划船", "哑铃侧平举"],
    names: [
      "哑铃卧推|Dumbbell Bench Press",
      "上斜哑铃卧推",
      "哑铃飞鸟",
      "上斜哑铃飞鸟",
      "哑铃地板卧推",
      "单臂哑铃划船",
      "胸托哑铃划船",
      "哑铃俯身划船",
      "哑铃肩推",
      "阿诺德推举",
      "哑铃侧平举",
      "哑铃前平举",
      "俯身反向飞鸟",
      "哑铃耸肩",
      "哑铃弯举",
      "锤式弯举",
      "上斜哑铃弯举",
      "集中弯举",
      "哑铃颈后臂屈伸",
      "哑铃仰卧臂屈伸",
      "哑铃臂后伸",
      "农夫行走",
    ],
  }),
  ...group({
    prefix: "dumbbell-lower",
    category: "strength",
    tracking: "sets",
    group: "哑铃下肢",
    equipment: "哑铃",
    muscles: ["股四头肌", "臀", "腘绳肌", "小腿"],
    popular: ["高脚杯深蹲", "哑铃罗马尼亚硬拉"],
    names: [
      "高脚杯深蹲|Goblet Squat",
      "哑铃深蹲",
      "哑铃罗马尼亚硬拉",
      "哑铃相扑深蹲",
      "哑铃箭步蹲",
      "哑铃反向箭步蹲",
      "哑铃侧弓步",
      "哑铃保加利亚分腿蹲",
      "哑铃登台阶",
      "单腿哑铃硬拉",
      "哑铃臀桥",
      "哑铃提踵",
    ],
  }),
  ...group({
    prefix: "machine-cable",
    category: "strength",
    tracking: "sets",
    group: "器械与绳索",
    equipment: "固定器械",
    muscles: ["胸", "背", "腿", "肩", "手臂"],
    popular: ["高位下拉", "坐姿划船", "腿举", "绳索下压"],
    names: [
      "史密斯深蹲",
      "史密斯卧推",
      "史密斯肩推",
      "史密斯臀推",
      "坐姿推胸",
      "蝴蝶机夹胸",
      "反向蝴蝶机飞鸟",
      "高位下拉",
      "反握高位下拉",
      "直臂下压",
      "坐姿划船",
      "单臂绳索划船",
      "绳索面拉|Face Pull",
      "绳索夹胸",
      "绳索侧平举",
      "绳索弯举",
      "绳索下压",
      "绳索过顶臂屈伸",
      "辅助引体向上",
      "辅助双杠臂屈伸",
      "腿举|Leg Press",
      "哈克深蹲|Hack Squat",
      "腿屈伸",
      "坐姿腿弯举",
      "俯卧腿弯举",
      "髋外展",
      "髋内收",
      "站姿提踵机",
      "坐姿提踵机",
      "背部伸展机",
    ],
  }),
  ...group({
    prefix: "bodyweight",
    category: "strength",
    tracking: "sets",
    group: "自重训练",
    equipment: "自重",
    muscles: ["全身", "核心"],
    popular: ["俯卧撑", "引体向上", "平板支撑", "徒手深蹲"],
    names: [
      "俯卧撑|Push-up",
      "跪姿俯卧撑",
      "上斜俯卧撑",
      "下斜俯卧撑",
      "钻石俯卧撑",
      "爆发俯卧撑",
      "引体向上|Pull-up",
      "反手引体向上|Chin-up",
      "澳式引体向上",
      "双杠臂屈伸|Dips",
      "徒手深蹲|Bodyweight Squat",
      "深蹲跳",
      "箭步蹲",
      "反向箭步蹲",
      "保加利亚分腿蹲",
      "单腿深蹲|Pistol Squat",
      "臀桥",
      "单腿臀桥",
      "提踵",
      "平板支撑|Plank",
      "侧平板支撑",
      "卷腹",
      "反向卷腹",
      "仰卧举腿",
      "悬垂举腿",
      "俄罗斯转体",
      "鸟狗式",
      "死虫式|Dead Bug",
      "登山跑|Mountain Climber",
      "波比跳|Burpee",
      "熊爬",
    ],
  }),
  ...group({
    prefix: "kettlebell-band",
    category: "strength",
    tracking: "sets",
    group: "壶铃与弹力带",
    equipment: "壶铃/弹力带",
    muscles: ["全身", "臀", "肩", "背"],
    names: [
      "壶铃摆动|Kettlebell Swing",
      "壶铃高脚杯深蹲",
      "壶铃硬拉",
      "壶铃抓举",
      "壶铃翻举",
      "壶铃土耳其起立",
      "壶铃风车",
      "壶铃农夫行走",
      "弹力带深蹲",
      "弹力带臀桥",
      "弹力带侧向行走",
      "弹力带划船",
      "弹力带下拉",
      "弹力带推胸",
      "弹力带肩推",
      "弹力带面拉",
      "弹力带外旋",
    ],
  }),
  ...group({
    prefix: "running",
    category: "running",
    tracking: "distance",
    group: "跑步",
    equipment: "跑鞋",
    muscles: ["心肺", "腿"],
    popular: ["户外跑步", "跑步机", "间歇跑"],
    names: [
      "户外跑步|路跑/Running",
      "跑步机",
      "轻松跑|Easy Run",
      "恢复跑",
      "长距离跑|LSD",
      "节奏跑|Tempo Run",
      "间歇跑|Intervals",
      "冲刺跑|Sprint",
      "坡度跑",
      "越野跑|Trail Running",
      "马拉松",
      "半程马拉松",
      "操场跑",
      "沙滩跑",
      "水中跑",
    ],
  }),
  ...group({
    prefix: "cardio",
    category: "cardio",
    tracking: "distance",
    group: "有氧器械",
    equipment: "有氧器械",
    muscles: ["心肺", "全身"],
    popular: ["户外骑行", "室内单车", "划船机", "跳绳"],
    names: [
      "户外骑行|自行车/Cycling",
      "公路骑行",
      "山地骑行",
      "室内单车|动感单车/Spinning",
      "椭圆机",
      "划船机",
      "滑雪机|SkiErg",
      "登山机",
      "台阶机",
      "风阻单车",
      "手摇功率车",
      "跳绳",
      "战绳",
    ],
  }),
  ...group({
    prefix: "swimming",
    category: "swimming",
    tracking: "swim",
    group: "游泳",
    equipment: "泳池/开放水域",
    muscles: ["心肺", "全身"],
    popular: ["自由泳", "蛙泳", "开放水域游泳"],
    names: [
      "自由泳|爬泳/Freestyle",
      "蛙泳|Breaststroke",
      "仰泳|Backstroke",
      "蝶泳|Butterfly",
      "个人混合泳|IM",
      "开放水域游泳",
      "浮潜",
      "踢腿练习",
      "划手练习",
      "夹板划手",
      "脚蹼游泳",
      "游泳间歇训练",
      "游泳耐力训练",
      "水中有氧",
    ],
  }),
  ...group({
    prefix: "outdoor",
    category: "outdoor",
    tracking: "distance",
    group: "户外耐力",
    equipment: "户外装备",
    muscles: ["心肺", "腿", "全身"],
    popular: ["步行", "徒步登山", "登山"],
    names: [
      "步行|Walking",
      "快走",
      "健走",
      "室内步行",
      "徒步|Hiking",
      "徒步登山",
      "登山|Mountaineering",
      "负重徒步|Rucking",
      "攀岩",
      "抱石",
      "越野滑雪",
      "高山滑雪",
      "单板滑雪",
      "雪鞋行走",
      "皮划艇",
      "赛艇",
      "桨板|SUP",
      "冲浪",
      "帆船",
      "轮滑",
      "滑板",
    ],
  }),
  ...group({
    prefix: "mobility",
    category: "mobility",
    tracking: "duration",
    group: "拉伸与恢复",
    equipment: "垫子/泡沫轴",
    muscles: ["灵活性", "恢复"],
    popular: ["全身拉伸", "泡沫轴放松", "肩颈拉伸"],
    names: [
      "全身拉伸",
      "肩颈拉伸",
      "胸椎灵活性",
      "肩关节灵活性",
      "髋关节灵活性",
      "踝关节灵活性",
      "腘绳肌拉伸",
      "股四头肌拉伸",
      "髂腰肌拉伸",
      "臀肌拉伸",
      "小腿拉伸",
      "动态热身",
      "跑前热身",
      "跑后拉伸",
      "力量训练热身",
      "泡沫轴放松",
      "筋膜球放松",
      "呼吸恢复训练",
      "冷身放松",
      "康复训练",
    ],
  }),
  ...group({
    prefix: "mindbody",
    category: "mindbody",
    tracking: "duration",
    group: "瑜伽与身心",
    equipment: "瑜伽垫",
    muscles: ["核心", "灵活性", "身心"],
    popular: ["瑜伽", "普拉提", "冥想"],
    names: [
      "瑜伽|Yoga",
      "流瑜伽|Vinyasa",
      "阴瑜伽",
      "哈他瑜伽",
      "阿斯汤伽瑜伽",
      "热瑜伽",
      "空中瑜伽",
      "孕产瑜伽",
      "普拉提|Pilates",
      "器械普拉提",
      "垫上普拉提",
      "太极",
      "八段锦",
      "冥想",
      "正念呼吸",
      "舞蹈",
      "尊巴|Zumba",
      "芭蕾把杆",
    ],
  }),
  ...group({
    prefix: "sports",
    category: "sports",
    tracking: "duration",
    group: "球类与综合运动",
    equipment: "运动场地",
    muscles: ["心肺", "全身", "协调"],
    popular: ["篮球", "足球", "羽毛球", "网球"],
    names: [
      "篮球",
      "三人篮球",
      "足球",
      "五人制足球",
      "橄榄球",
      "美式橄榄球",
      "排球",
      "沙滩排球",
      "羽毛球",
      "网球",
      "乒乓球",
      "壁球",
      "匹克球|Pickleball",
      "手球",
      "棒球",
      "垒球",
      "高尔夫",
      "冰球",
      "曲棍球",
      "拳击",
      "自由搏击",
      "泰拳",
      "综合格斗|MMA",
      "跆拳道",
      "柔道",
      "巴西柔术|BJJ",
      "击剑",
      "射箭",
    ],
  }),
];

export const EQUIPMENT_OPTIONS = Array.from(
  new Set(EXERCISES.map((exercise) => exercise.equipment)),
).sort((a, b) => a.localeCompare(b, "zh-CN"));

export function searchExercises(
  query: string,
  category: ExerciseCategory | "all",
  equipment: string | "all",
): Exercise[] {
  const normalized = query.trim().toLowerCase();
  return EXERCISES.filter((exercise) => {
    if (category !== "all" && exercise.category !== category) return false;
    if (equipment !== "all" && exercise.equipment !== equipment) return false;
    if (!normalized) return true;
    return [
      exercise.name,
      exercise.group,
      exercise.equipment,
      ...exercise.aliases,
      ...exercise.muscles,
      CATEGORY_META[exercise.category].label,
    ]
      .join(" ")
      .toLowerCase()
      .includes(normalized);
  });
}

export function getExercise(id: string): Exercise | undefined {
  return EXERCISES.find((exercise) => exercise.id === id);
}

