/** 地标唯一数据源。0 全貌 / 1 大陆 / 2 生态 / 3 地表；maxDetailLevel 控制退场。 */
export const LANDMARKS = [
  {
    id: "west-continent",
    name: "西境造山带",
    type: "desert",
    latitude: 22,
    longitude: -31,
    minDetailLevel: 0,
    maxDetailLevel: 1,
    priority: 100,
    labelKind: "region",
    description: "西部连续山系与赤铜高原",
  },
  {
    id: "monsoon-continent",
    name: "季风大陆",
    type: "forest",
    latitude: -18,
    longitude: 27,
    minDetailLevel: 0,
    maxDetailLevel: 1,
    priority: 100,
    labelKind: "region",
    description: "季风森林覆盖的南部大陆",
  },
  {
    id: "basalt-ridge",
    name: "层岩山脊",
    type: "desert",
    latitude: 27,
    longitude: -36,
    altitude: 1.18,
    minDetailLevel: 3,
    description: "造山带中的层状裸岩地标",
    model: "/assets/landmarks/basalt.glb",
    modelScale: 0.018,
    maxDetailLevel: 3,
    priority: 95,
    labelKind: "place",
    revealLayer: "landmarks",
  },
  {
    id: "glacier-tongue",
    name: "裂隙冰舌",
    type: "glacier",
    latitude: 68,
    longitude: 9,
    altitude: 1.12,
    minDetailLevel: 3,
    description: "极地冰盖边缘的破碎冰舌",
    model: "/assets/landmarks/glacier.glb",
    modelScale: 0.014,
    maxDetailLevel: 3,
    priority: 95,
    labelKind: "place",
    revealLayer: "landmarks",
  },
  {
    id: "polar-glacier",
    name: "冰川",
    type: "glacier",
    latitude: 70,
    longitude: 4,
    altitude: 1.18,
    minDetailLevel: 0,
    description: "位于北部极区的永久冰川与浮冰带",
    maxDetailLevel: 1,
    priority: 90,
    labelKind: "region",
  },
  {
    id: "open-ocean",
    name: "海洋",
    type: "ocean",
    latitude: 6,
    longitude: 65,
    altitude: 1.08,
    minDetailLevel: 0,
    description: "大陆以外的深蓝色开放水域",
    maxDetailLevel: 1,
    priority: 65,
    labelKind: "region",
  },
  {
    id: "living-river",
    name: "河流",
    type: "river",
    latitude: 18,
    longitude: 9.48,
    altitude: 1.16,
    minDetailLevel: 1,
    description: "由北部冰川流向季风大陆的主要水道",
    maxDetailLevel: 2,
    priority: 85,
    labelKind: "place",
  },
  {
    id: "monsoon-forest",
    name: "森林",
    type: "forest",
    latitude: -18,
    longitude: 29,
    altitude: 1.17,
    minDetailLevel: 2,
    description: "季风大陆中部的森林和生态储备区域",
    maxDetailLevel: 2,
    priority: 85,
    labelKind: "place",
  },
  {
    id: "western-desert",
    name: "荒漠",
    type: "desert",
    latitude: 10,
    longitude: -42,
    altitude: 1.17,
    minDetailLevel: 1,
    description: "造山带西侧的干旱高原与裸露岩层",
    maxDetailLevel: 2,
    priority: 80,
    labelKind: "place",
  },
  {
    id: "meltwater-lake",
    name: "融水湖",
    type: "river",
    latitude: 2,
    longitude: 12.8,
    minDetailLevel: 2,
    maxDetailLevel: 3,
    priority: 75,
    description: "冰川融水汇入的内陆湖泊",
  },
  {
    id: "wetland-bank",
    name: "河岸湿地",
    type: "forest",
    latitude: -14,
    longitude: 19,
    minDetailLevel: 3,
    maxDetailLevel: 3,
    priority: 70,
    description: "低矮植被密集的湿润河岸",
  },
  {
    id: "copper-strata",
    name: "赤铜岩层",
    type: "desert",
    latitude: 23,
    longitude: -30,
    minDetailLevel: 3,
    maxDetailLevel: 3,
    priority: 90,
    description: "海拔与坡度共同塑造的层状裸岩",
  },
  {
    id: "conifer-canopy",
    name: "针叶林冠",
    type: "forest",
    latitude: -18,
    longitude: 27,
    minDetailLevel: 3,
    maxDetailLevel: 3,
    priority: 90,
    description: "沿湿度与海拔分布的针叶林群落",
  },
]

export const TERRAIN_TYPES = {
  glacier: {
    displayName: "冰川",
    definition: "永久积雪、冰盖和破碎浮冰组成的高纬地貌",
    color: "#91b9e2",
  },
  ocean: {
    displayName: "海洋",
    definition: "大陆轮廓以外、具有洋流纹理的开放水域",
    color: "#25437b",
  },
  river: {
    displayName: "河流",
    definition: "从极地冰川汇入湖泊并流向南部大陆的连续水系",
    color: "#43d2c1",
  },
  forest: {
    displayName: "森林",
    definition: "灰绿色针叶植被和生态群落集中分布的区域",
    color: "#288678",
  },
  desert: {
    displayName: "荒漠",
    definition: "降水稀少、以铜橙色岩台和裸露峡谷为主的区域",
    color: "#da785a",
  },
}
