/** 地标唯一数据源。0 天际 / 1 板块 / 2 气候 / 3 生态 / 4 地表；maxDetailLevel 控制退场。 */
export const LANDMARKS = [
  {
    id: "west-continent",
    name: "西境造山带",
    type: "desert",
    latitude: 22,
    longitude: -31,
    minDetailLevel: 1,
    maxDetailLevel: 1,
    priority: 100,
    labelKind: "region",
    description: "西部连续山系与赤铜高原",
  },
  {
    id: "monsoon-continent",
    name: "季风大陆",
    type: "forest",
    latitude: -18,
    longitude: 27,
    minDetailLevel: 1,
    maxDetailLevel: 1,
    priority: 100,
    labelKind: "region",
    description: "季风森林覆盖的南部大陆",
  },
  {
    id: "red-sand-continent",
    name: "赤砂大陆",
    type: "desert",
    latitude: 31,
    longitude: -148,
    minDetailLevel: 1,
    maxDetailLevel: 1,
    priority: 96,
    labelKind: "region",
    description: "风蚀高原和沙漠台地形成的干旱大陆",
  },
  {
    id: "cape-bay-continent",
    name: "岬湾大陆",
    type: "forest",
    latitude: -28,
    longitude: -130,
    minDetailLevel: 1,
    maxDetailLevel: 1,
    priority: 76,
    labelKind: "region",
    description: "南部大洋中带有双岬和内凹海湾的小型大陆",
  },
  {
    id: "southwind-continent",
    name: "南风大陆",
    type: "forest",
    latitude: -44,
    longitude: 83,
    minDetailLevel: 1,
    maxDetailLevel: 1,
    priority: 75,
    labelKind: "region",
    description: "南部高纬海域的狭长陆块与起伏高地",
  },
  {
    id: "east-mist-continent",
    name: "东岚大陆",
    type: "forest",
    latitude: 36,
    longitude: 104,
    minDetailLevel: 1,
    maxDetailLevel: 1,
    priority: 75,
    labelKind: "region",
    description: "星链群岛北侧拥有曲折海岸的小型大陆",
  },
  {
    id: "basalt-ridge",
    name: "层岩山脊",
    type: "desert",
    latitude: 27,
    longitude: -36,
    altitude: 1.18,
    minDetailLevel: 4,
    description: "造山带中的层状裸岩地标",
    model: "/assets/landmarks/basalt.glb",
    modelScale: 0.018,
    maxDetailLevel: 4,
    priority: 95,
    labelKind: "place",
    revealLayer: "landmarks",
  },
  {
    id: "glacier-tongue",
    name: "裂隙冰舌",
    type: "glacier",
    latitude: 68,
    longitude: 9,
    altitude: 1.12,
    minDetailLevel: 4,
    description: "极地冰盖边缘的破碎冰舌",
    model: "/assets/landmarks/glacier.glb",
    modelScale: 0.014,
    maxDetailLevel: 4,
    priority: 95,
    labelKind: "place",
    revealLayer: "landmarks",
  },
  {
    id: "polar-glacier",
    name: "万重冰原",
    type: "glacier",
    latitude: 70,
    longitude: 4,
    altitude: 1.18,
    minDetailLevel: 1,
    description: "位于北部极区的永久冰川与浮冰带",
    maxDetailLevel: 1,
    priority: 90,
    labelKind: "region",
  },
  {
    id: "open-ocean",
    name: "深蓝寰海",
    type: "ocean",
    latitude: 6,
    longitude: 65,
    altitude: 1.08,
    minDetailLevel: 1,
    description: "大陆以外的深蓝色开放水域",
    maxDetailLevel: 1,
    priority: 65,
    labelKind: "region",
  },
  {
    id: "star-chain-islands",
    name: "星链群岛",
    type: "ocean",
    latitude: 8,
    longitude: 83,
    minDetailLevel: 1,
    maxDetailLevel: 2,
    priority: 82,
    labelKind: "region",
    description: "散布在中央大洋中的火山岛弧与浅海陆架",
  },
  {
    id: "living-river",
    name: "天脉长河",
    type: "river",
    latitude: 18,
    longitude: 9.48,
    altitude: 1.16,
    minDetailLevel: 2,
    description: "由北部冰川流向季风大陆的主要水道",
    maxDetailLevel: 3,
    priority: 85,
    labelKind: "place",
  },
  {
    id: "monsoon-forest",
    name: "季风林海",
    type: "forest",
    latitude: -18,
    longitude: 29,
    altitude: 1.17,
    minDetailLevel: 3,
    description: "季风大陆中部的森林和生态储备区域",
    maxDetailLevel: 3,
    priority: 85,
    labelKind: "place",
  },
  {
    id: "western-desert",
    name: "风蚀荒原",
    type: "desert",
    latitude: 10,
    longitude: -42,
    altitude: 1.17,
    minDetailLevel: 2,
    description: "造山带西侧的干旱高原与裸露岩层",
    maxDetailLevel: 3,
    priority: 80,
    labelKind: "place",
  },
  {
    id: "meltwater-lake",
    name: "月镜融水湖",
    type: "river",
    latitude: 2,
    longitude: 12.8,
    minDetailLevel: 3,
    maxDetailLevel: 4,
    priority: 75,
    description: "冰川融水汇入的内陆湖泊",
  },
  {
    id: "wetland-bank",
    name: "河岸湿地",
    type: "forest",
    latitude: -14,
    longitude: 19,
    minDetailLevel: 4,
    maxDetailLevel: 4,
    priority: 70,
    description: "低矮植被密集的湿润河岸",
  },
  {
    id: "copper-strata",
    name: "赤铜岩层",
    type: "desert",
    latitude: 23,
    longitude: -30,
    minDetailLevel: 4,
    maxDetailLevel: 4,
    priority: 90,
    description: "海拔与坡度共同塑造的层状裸岩",
  },
  {
    id: "conifer-canopy",
    name: "针叶林冠",
    type: "forest",
    latitude: -18,
    longitude: 27,
    minDetailLevel: 4,
    maxDetailLevel: 4,
    priority: 90,
    description: "沿湿度与海拔分布的针叶林群落",
  },

  // 地貌专名在地图放大后逐级展开；经纬度贴合共享高度场中的地貌。
  {
    id: "cloudcut-ridge",
    name: "斩云山脊",
    type: "desert",
    latitude: 32,
    longitude: -30,
    altitude: 1.12,
    minDetailLevel: 2,
    maxDetailLevel: 3,
    priority: 82,
    labelKind: "place",
    description: "西境造山带中抬升于赭铜高原上的长脊地形",
  },
  {
    id: "emberwind-terrace",
    name: "烬风台地",
    type: "desert",
    latitude: 36,
    longitude: -154,
    altitude: 1.12,
    minDetailLevel: 2,
    maxDetailLevel: 3,
    priority: 82,
    labelKind: "place",
    description: "赤砂大陆北部受强风侵蚀的阶状高原",
  },
  {
    id: "red-canyon-river",
    name: "赤峡长河",
    type: "river",
    latitude: 25,
    longitude: -141,
    altitude: 1.12,
    minDetailLevel: 2,
    maxDetailLevel: 3,
    priority: 86,
    labelKind: "place",
    description: "穿过赤砂高地与层状峡谷的主河道",
  },
  {
    id: "windshadow-basin",
    name: "雨影盆地",
    type: "desert",
    latitude: 22,
    longitude: -32,
    altitude: 1.12,
    minDetailLevel: 3,
    maxDetailLevel: 4,
    priority: 74,
    labelKind: "place",
    description: "西境山系背风侧的干旱盆地与裸岩坡地",
  },
  {
    id: "cape-twin-headlands",
    name: "岬湾双岬",
    type: "forest",
    latitude: -24,
    longitude: -132,
    altitude: 1.12,
    minDetailLevel: 3,
    maxDetailLevel: 4,
    priority: 76,
    labelKind: "place",
    description: "南部海湾两侧相对伸出的岩质岬角",
  },
  {
    id: "falling-star-delta",
    name: "沉星三角洲",
    type: "river",
    latitude: -37,
    longitude: -136,
    altitude: 1.02,
    minDetailLevel: 3,
    maxDetailLevel: 4,
    priority: 80,
    labelKind: "place",
    description: "岬湾大陆南端多股支流交织的潮汐河口",
  },
  {
    id: "southwind-river-valley",
    name: "南风河谷",
    type: "river",
    latitude: -42,
    longitude: 80,
    altitude: 1.12,
    minDetailLevel: 2,
    maxDetailLevel: 3,
    priority: 82,
    labelKind: "place",
    description: "南风大陆中部由山地支流汇入干流的宽谷",
  },
  {
    id: "eastmist-river-valley",
    name: "岚川谷地",
    type: "river",
    latitude: 43,
    longitude: 100,
    altitude: 1.12,
    minDetailLevel: 2,
    maxDetailLevel: 3,
    priority: 82,
    labelKind: "place",
    description: "东岚大陆北部沿主河道展开的湿润河谷",
  },
  {
    id: "eastmist-cloud-steps",
    name: "云阶高原",
    type: "forest",
    latitude: 39,
    longitude: 108,
    altitude: 1.12,
    minDetailLevel: 3,
    maxDetailLevel: 4,
    priority: 74,
    labelKind: "place",
    description: "东岚大陆内陆由宽缓台地和低山肩部组成的高原",
  },
  {
    id: "monsoon-green-ridge",
    name: "青雨岭",
    type: "forest",
    latitude: -27,
    longitude: 26,
    altitude: 1.12,
    minDetailLevel: 3,
    maxDetailLevel: 4,
    priority: 74,
    labelKind: "place",
    description: "季风大陆北缘林地与起伏高地交错的山岭",
  },
  {
    id: "far-dawn-fjord",
    name: "远昼峡湾",
    type: "glacier",
    latitude: 76,
    longitude: -133,
    altitude: 1.02,
    minDetailLevel: 2,
    maxDetailLevel: 3,
    priority: 83,
    labelKind: "place",
    description: "北部冰盖西缘深入陆地的曲折潮汐峡湾",
  },
  {
    id: "silver-arc-fjord",
    name: "银弧峡湾",
    type: "glacier",
    latitude: 71,
    longitude: -59,
    altitude: 1.02,
    minDetailLevel: 2,
    maxDetailLevel: 3,
    priority: 80,
    labelKind: "place",
    description: "冰原东侧沿弧形海岸凿出的狭长海湾",
  },
  {
    id: "shardlight-fjord",
    name: "碎光冰峡",
    type: "glacier",
    latitude: 68,
    longitude: 18,
    altitude: 1.12,
    minDetailLevel: 2,
    maxDetailLevel: 3,
    priority: 83,
    labelKind: "place",
    description: "冰川台地间受侵蚀形成的分段冰峡与融水槽",
  },
  {
    id: "coldstar-channel",
    name: "寒星海峡",
    type: "glacier",
    latitude: 72,
    longitude: 140,
    altitude: 1.02,
    minDetailLevel: 2,
    maxDetailLevel: 3,
    priority: 80,
    labelKind: "place",
    description: "东部冰缘冰岛之间宽窄变化的潮汐水道",
  },
]

export const TERRAIN_TYPES = {
  glacier: {
    displayName: "冰川",
    definition: "永久积雪、冰盖和破碎浮冰组成的高纬地貌",
    color: "#91b9e2",
  },
  ocean: {
    displayName: "海洋",
    definition: "大陆轮廓以外、具有洋流纹理的开放水域",
    color: "#25437b",
  },
  river: {
    displayName: "河流",
    definition: "从极地冰川汇入湖泊并流向南部大陆的连续水系",
    color: "#43d2c1",
  },
  forest: {
    displayName: "森林",
    definition: "灰绿色针叶植被和生态群落集中分布的区域",
    color: "#288678",
  },
  desert: {
    displayName: "荒漠",
    definition: "降水稀少、以铜橙色岩台和裸露峡谷为主的区域",
    color: "#da785a",
  },
}
